import 'dotenv/config';

export const config = {
  NODE_ENV: process.env.NODE_ENV,
  PORT: process.env.PORT,

  APP_BACKEND_PREFIX: process.env.APP_BACKEND_PREFIX,
  APP_CORS_WHITELIST_URLS: process.env.APP_CORS_WHITELIST_URLS,

  MONGODB_URL: process.env.MONGODB_URL,

  GOOGLE_DRIVE_ROOT_FOLDER_ID: process.env.GOOGLE_DRIVE_ROOT_FOLDER_ID,

  GOOGLE_DRIVE_TYPE: process.env.GOOGLE_DRIVE_TYPE,
  GOOGLE_DRIVE_PROJECT_ID: process.env.GOOGLE_DRIVE_PROJECT_ID,
  GOOGLE_DRIVE_PRIVATE_KEY_ID: process.env.GOOGLE_DRIVE_PRIVATE_KEY_ID,
  GOOGLE_DRIVE_PRIVATE_KEY: process.env.GOOGLE_DRIVE_PRIVATE_KEY,
  GOOGLE_DRIVE_CLIENT_EMAIL: process.env.GOOGLE_DRIVE_CLIENT_EMAIL,
  GOOGLE_DRIVE_CLIENT_ID: process.env.GOOGLE_DRIVE_CLIENT_ID,
  GOOGLE_DRIVE_AUTH_URI: process.env.GOOGLE_DRIVE_AUTH_URI,
  GOOGLE_DRIVE_TOKEN_URI: process.env.GOOGLE_DRIVE_TOKEN_URI,
  GOOGLE_DRIVE_AUTH_PROVIDER_CERT_URL:
    process.env.GOOGLE_DRIVE_AUTH_PROVIDER_CERT_URL,
  GOOGLE_DRIVE_CLIENT_CERT_URL: process.env.GOOGLE_DRIVE_CLIENT_CERT_URL,
  GOOGLE_DRIVE_UNIVERSE_DOMAIN: process.env.GOOGLE_DRIVE_UNIVERSE_DOMAIN,

  GOOGLE_DRIVE_SCOPE: process.env.GOOGLE_DRIVE_SCOPE,

  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER,
};
